apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      run: demo
    name: demo
    namespace: demo
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: demo
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: demo
      spec:
        containers:
        - env:
          - name: PORT
            value: "8080"
          - name: DB_CONNECTION_STRING
            value: mongodb://mongo-mongodb.default.svc.cluster.local
          - name: INSTRUMENTATION_KEY
            valueFrom:
              secretKeyRef:
                name: appinsightskey
                key: instrumentation-key
          image: ivandal77/demo
          imagePullPolicy: Always
          name: demo
          ports:
          - containerPort: 8080
            protocol: TCP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
